set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'kchmck/vim-coffee-script'

" UI
" Bundle 'bling/vim-airline'
Bundle 'altercation/solarized'
Bundle 'flazz/vim-colorschemes'

" Code navigation
" Bundle 'tpope/vim-cucumber'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'nelstrom/vim-visual-star-search'
Bundle 'tsaleh/vim-matchit'

" Registers
" Bundle 'vim-scripts/YankRing.vim'
Bundle 'kana/vim-fakeclip'

" Version control
Bundle 'tpope/vim-fugitive'
Bundle 'gregsexton/gitv'
Bundle 'airblade/vim-gitgutter'

" Autocompletion
Bundle 'Shougo/neocomplete'
Bundle 'Shougo/neosnippet'
Bundle 'Shougo/neosnippet-snippets'
Bundle 'Shougo/vimshell'
Bundle 'scrooloose/syntastic'
Bundle 'tpope/vim-endwise'
Bundle 'file:///Users/stevemartin/Projects/emmet-vim'

" Resource Navigation
Bundle 'scrooloose/nerdtree'
Bundle 'vim-scripts/buflist'
Bundle 'vim-scripts/LustyJuggler'

" Search
Bundle 'kien/ctrlp.vim'
Bundle 'mileszs/ack.vim'
Bundle 'tyok/nerdtree-ack'

" Formatting
Bundle 'tpope/vim-commentary'
Bundle 'godlygeek/tabular'

" Javascript
Bundle 'pangloss/vim-javascript'
Bundle 'file:///Users/stevemartin/Projects/angular.vim'
" Bundle 'stevemartin/angular.vim'

" Ruby
Bundle 'vim-ruby/vim-ruby'
Bundle 'tpope/vim-rvm'
Bundle 'tpope/vim-rails'
Bundle 'ngmy/vim-rubocop'
Bundle 'ecomba/vim-ruby-refactoring'

" Data
Bundle 'vim-scripts/dbext.vim'

" SVG
Bundle 'vim-scripts/svg.vim'

" Shortcuts
" Bundle 'msanders/snipmate.vim'
Bundle 'Shougo/neosnippet'

" Editing
Bundle 'sjl/gundo.vim'
Bundle 'tpope/vim-surround'

" Testing
Bundle 'h1mesuke/vim-unittest'
Bundle 'kana/vim-vspec'

" Windowing
Bundle 'benmills/vimux'

" Utility
Bundle 'Shougo/vimproc'
" Bundle 'Shougo/context_filetype'
