set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle'
Plugin 'kchmck/vim-coffee-script'

" UI
Plugin 'bling/vim-airline'
Plugin 'flazz/vim-colorschemes'

" Code navigation
" Plugin 'tpope/vim-cucumber'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'nelstrom/vim-visual-star-search'
Plugin 'vim-scripts/matchit.zip'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'lmeijvogel/vim-yaml-helper'

" Registers
" Plugin 'vim-scripts/YankRing.vim'
Plugin 'kana/vim-fakeclip'

" Version control
Plugin 'tpope/vim-fugitive'
Plugin 'gregsexton/gitv'
Plugin 'airblade/vim-gitgutter'
" Plugin 'rickhowe/diffchar.vim'

" Autocompletion
" Plugin 'Valloric/YouCompleteMe'
Plugin 'Shougo/neocomplete'
" Plugin 'Shougo/neosnippet'
" Plugin 'Shougo/neosnippet-snippets'
Plugin 'Shougo/vimshell'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-endwise'
Plugin 'mattn/emmet-vim'
" Plugin 'file:///Users/stevemartin/Projects/emmet-vim'

" Resource Navigation
Plugin 'scrooloose/nerdtree'
Plugin 'vim-scripts/buflist'
" Plugin 'vim-scripts/LustyJuggler'

" Search
Plugin 'kien/ctrlp.vim'
" Plugin 'mileszs/ack.vim'
" Plugin 'tyok/nerdtree-ack'
Plugin 'rking/ag.vim'
Plugin 'taiansu/nerdtree-ag'

" Formatting
Plugin 'tpope/vim-commentary'
Plugin 'godlygeek/tabular'
Plugin 'groenewege/vim-less'
Plugin 'digitaltoad/vim-jade'

" Javascript
Plugin 'pangloss/vim-javascript'
" Plugin 'file:///Users/stevemartin/Projects/angular.vim'
Plugin 'stevemartin/angular.vim'
Plugin 'othree/yajs.vim'

" Ruby
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rvm'
Plugin 'tpope/vim-rails'
Plugin 'ngmy/vim-rubocop'
Plugin 'ecomba/vim-ruby-refactoring'

" Data
Plugin 'vim-scripts/dbext.vim'

" SVG
Plugin 'vim-scripts/svg.vim'

" Editing
Plugin 'sjl/gundo.vim'
Plugin 'tpope/vim-surround'

" Testing
" Plugin 'h1mesuke/vim-unittest'
" Plugin 'kana/vim-vspec'

" Windowing
" Plugin 'benmills/vimux'

" Utility
Plugin 'Shougo/vimproc'
" Plugin 'Shougo/context_filetype'

call vundle#end()
filetype plugin indent on
