let mapleader = "\\"
" File navigation
nnoremap <leader>nt :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFind<CR>
nnoremap <leader>p :CtrlP<CR>

" Vim admin
nnoremap <leader>so :source ~/.vimrc<CR>
nnoremap <leader>ev :e ~/.vimrc<CR>
nnoremap <leader>es :e ~/.vim/settings.module<CR>
nnoremap <leader>em :e ~/.vim/mappings.module<CR>
nnoremap <leader>eb :e ~/.vim/bundle.module<CR>

" File navigation
nnoremap <leader>co :copen<CR>
nnoremap <leader>cn :cn<CR>
nnoremap <leader>cnf :cnf<CR>

nnoremap <leader>cp :cp<CR>
nnoremap <leader>cpf :cpf<CR>

nnoremap <leader>fn :NERDTreeClose<CR>:cn<CR>:NERDTreeFind<CR><C-w>l
nnoremap <leader>fnf :NERDTreeClose<CR>:cnf<CR>:NERDTreeFind<CR><C-w>l

nnoremap <leader>fp :NERDTreeClose<CR>:cp<CR>:NERDTreeFind<CR><C-w>l
nnoremap <leader>fpf :NERDTreeClose<CR>:cpf<CR>:NERDTreeFind<CR><C-w>l

" Tab navigation
nnoremap <leader>tN :tabnew<CR>
nnoremap <leader>tn :tabnext<CR>
nnoremap <leader>tp :tabprevious<CR>
nnoremap <leader>q :q<CR>

" Git mappings
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>gp :Git push<CR>
nnoremap <leader>gpl :Git push<CR>

" View modification
nnoremap <leader>nu :set nu<CR>
nnoremap <leader>nnu :set nonu<CR>

nnoremap <leader>sp :set paste<CR>
nnoremap <leader>snp :set nopaste<CR>

" Code traversal
nnoremap <leader>tg :!ctags -R --exclude=.git --exclude=log * `echo $GEM_HOME`/gems/*<CR>
