let mapleader = "\\"
" Text editing
nnoremap <leader>un :GundoToggle<CR>
nnoremap <leader>hash :%s/:\([^ ]*\)\(\s*\)=>/\1:/g \| :%s/"\([^ ]*\)\(\s*\)"\s*=>/\1:/g \| :%s/'\([^ ]*\)\(\s*\)'\s*=>/\1:/g<CR>
nnoremap <leader>syhash :%s/:\([^ ]*\)\(\s*\)=>/\1:/g<CR>
nnoremap <leader>dhash :%s/"\([^ ]*\)\(\s*\)"\s*=>/\1:/g<CR>
nnoremap <leader>shash :%s/'\([^ ]*\)\(\s*\)'\s*=>/\1:/g<CR>

"camelize
nnoremap <leader>u /\w\+_<CR>
nnoremap <leader>c f_b~f_x~ " camel case
nnoremap <leader>vcj ve:s/\%V_\(\w\)/\U\1/g<CR><ESC>e " visual camelcase word javascript :   s/_\(\w\)/\U\1/g
nnoremap <leader>vcc ~ve:s/\%V_\(\w\)/\U\1/g<CR><ESC>e " visual camelcase word :   s/_\(\w\)/\U\1/g
nnoremap <leader>jc f_x~ " javascript camel case
nnoremap <leader>vsn vuve:s/\%V\([A-Z]\)/_\L\1/g<CR><ESC>e " visual snake case
nnoremap <leader>uu /\u<CR>~hi_<esc>

" snake_case_times_three.snake_case_times_four_things
" CamelCaseTimesThree.camelCaseTimesFourThings

" Vim admin
nnoremap <leader>so :source ~/.vimrc<CR>
nnoremap <leader>ev :e ~/.vimrc<CR>
nnoremap <leader>es :e ~/.vim/settings.module<CR>
nnoremap <leader>eh :e ~/.vim/syntax.module<CR>
nnoremap <leader>em :e ~/.vim/mappings.module<CR>
nnoremap <leader>eb :e ~/.vim/bundle.module<CR>
nnoremap <leader>er :e ~/.vim/regex.module<CR>
nnoremap <leader>ed :e ~/.vim/sql.module<CR>
nnoremap <leader>ec :e ~/.vim/cheatsheet.txt<CR>

" File navigation
nnoremap <leader>co :copen<CR>
nnoremap <leader>cn :cn<CR>
nnoremap <leader>cnf :cnf<CR>

nnoremap <leader>cp :cp<CR>
nnoremap <leader>cpf :cpf<CR>

nnoremap <leader>nt :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFind<CR>
nnoremap <leader>p :CtrlP<CR>
nnoremap <leader>pm :CtrlPMRU<CR>
nnoremap <leader>b :buffers<CR>
nnoremap <leader>fn :NERDTreeClose<CR>:cn<CR>:NERDTreeFind<CR><C-w>l
nnoremap <leader>fnf :NERDTreeClose<CR>:cnf<CR>:NERDTreeFind<CR><C-w>l

nnoremap <leader>fp :NERDTreeClose<CR>:cp<CR>:NERDTreeFind<CR><C-w>l
nnoremap <leader>fpf :NERDTreeClose<CR>:cpf<CR>:NERDTreeFind<CR><C-w>l

" File manipulation
" imap ;w <Esc>:w<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>wq :wq<CR>

" Tab navigation
nnoremap <leader>t :tabnew<CR>
nnoremap <leader>tc :tabclose<CR>
nnoremap <leader>q :q<CR>

" Git mappings
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gcd :Gedit<CR><C-w>h :q<CR><C-w>k
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>gp :Git push<CR>
nnoremap <leader>gpl :Git push<CR>
nnoremap <leader>ga% :Git add %<CR>

nnoremap <leader>gv :Gitv<CR>
nnoremap <leader>gvf :Gitv!<CR>

" View modification
nnoremap <leader>nu :set nu<CR>
nnoremap <leader>nnu :set nonu<CR>

nnoremap <leader>sp :set paste<CR>
nnoremap <leader>snp :set nopaste<CR>

" Code traversal
nnoremap <leader>tg :!/usr/local/bin/ctags -R --exclude=.git --exclude=log * `echo $GEM_HOME`/gems/*<CR>
imap ;; <Esc>l

" Code editing
