source ~/.vim/settings.module
source ~/.vim/neocomplete.bundle
source ~/.vim/mappings.module
source ~/.vim/bundle.module
source ~/.vim/syntax.module
colorscheme 256-grayvim
colorscheme Tomorrow
colorscheme Tomorrow-Night
source ~/.vim/colours.module
